// Generated by CoffeeScript 1.6.2
(function() {
  var fs, redis;

  fs = require('fs');

  redis = require('redis');

  process.env.NODE_ENV = "test";

  module.exports = {
    getRedisClient: function() {
      var config, redisConfigPath;

      redisConfigPath = __dirname + "/../../test/redis.json";
      config = {};
      if (fs.existsSync(redisConfigPath)) {
        config = JSON.parse(fs.readFileSync(redisConfigPath));
      }
      return redis.createClient(config.port, config.host, config.options);
    }
  };

}).call(this);
