// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    setnx_pexpire: "local result = redis.call('SETNX', KEYS[1], ARGV[1])\nif result == 1 then\n  redis.call('PEXPIRE', KEYS[1], ARGV[2])\nend\nreturn result",
    delequal: "local deleted = 0\nif redis.call('GET', KEYS[1]) == ARGV[1] then\n  return redis.call('DEL', KEYS[1])\nend\nreturn 0"
  };

}).call(this);
